let count=0;
function generate_qr() {
    document.querySelector("#qr-image").style.display = "block";
    let QRtext = document.querySelector("#text").value;
    if (QRtext.trim().length == 0) {
        document.querySelectorAll("qr-image.error").innerHTML = "Please enter the text..";
        document.querySelectorAll("#img").style.display = "none";

    }
    else {
        document.querySelector("#img").style.display = "block";
        document.querySelector("#qr-image .error").innerHTML = "";
        document.querySelector("#img").src = " https://api.qrserver.com/v1/create-qr-code/?size=240x240&data=" + QRtext;
    
        
        let link = document.querySelector("#qr-image a[download]");
        if (link) {
            link.remove();
        }
        link = document.createElement("a");
        link.href = document.querySelector("#img").src;
        link.download = "qr-code.png";
        link.innerHTML = "Download QR Code";
        link.style.display = "block";
        link.style.textAlign = "center";
        link.style.marginTop = "10px";
        link.style.marginBottom = "10px";
        document.querySelector("#qr-image").appendChild(link);
        count++;
        document.querySelector("#count").textContent = "Number of QR codes generated by you: " + count;
    }





}

